# This is a basic workflow to help you get started with Actions

name: ytb

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

#      - name: install rclone
#        run: |
#          sudo -v ; curl https://rclone.org/install.sh | sudo bash
#      - name: write rclone config
#        run: |
#          mkdir -p ~/.config/rclone/
#          cat << EOF > ~/.config/rclone/rclone.conf
#          ${{secrets.RCLONE_CONFIG}} 
#          EOF
      - name: install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: install aria2
        run: |
          sudo apt-get install aria2
      - name: write youtube cookies
        run: |
          cat << EOF > cookies.txt
          ${{secrets.YOUTUBE_COOKIES}} 
          EOF
      - name: download
        run: |
          yt-dlp --config-location config.txt
          
#      - name: upload to onedrive by rclone
#        run: |
#          rclone copy ./downloads asmr:/downloads -P
#      - name: upload
#        run: |
#          curl -fsSL git.io/file-transfer | sh
#          ./transfer wet --no-progress ./downloads/ 2>&1 | tee anon.log
#          echo "::warning file=anonfiles.com::$(cat anon.log | grep https)"
#          echo "::set-output name=url::$(cat anon.log | grep https | cut -f3 -d" ")"
#
#      - name: set up go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.18
#
#      - name: upload local
#        run: |
#          go run main.go
